# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f79dbba370ee58d6f74ce708f0a8dd3a991677f217e683d3067b68b8b534ce41283a2264da8f2a437ee42eb205d5946ad778920e773ecd15ee03166d3690ead

test:
  secret_key_base: 18724372998374386e32880b6d3c8e758deef922b5c640e8f16050d76c5c04f7e184c3bf2c6d4619e123b8f6c21cdad57094ea1ee0f47dbf44a9343301a86341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
